# Generated by Django 4.2.7 on 2023-11-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshowroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
