# Generated by Django 4.2.7 on 2023-11-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshowroom', '0006_alter_car_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
