# Generated by Django 4.2.7 on 2023-11-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshowroom', '0007_alter_car_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='des',
            field=models.CharField(default='Default Description', max_length=1000),
        ),
    ]
