# Generated by Django 4.2.7 on 2023-11-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshowroom', '0009_testdrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrive',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
