# Generated by Django 4.2.7 on 2023-11-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshowroom', '0010_testdrive_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
    ]
